#!/usr/bin/env node

const program = require("commander"),
  packageInfo = require("./package.json"),
  proxyApp = require("./app/app");

program
  .version(packageInfo.version)
  .option("-p, --port [value]", "proxy port", "8001")
  .option("-w, --web [value]", "web GUI port", "8002")
  .option("--path <rule file path | default on sample/source.json>", "json path")
  .option("-c, --clean", "Clear cache")
  .parse(process.argv);

return proxyApp.startProxy(program);
